title: Under Constraints
description: notes on conservative modeling and physical inference
author: Anuraag Sharma

baseurl: ""
url: "https://mdanuraag.github.io"

theme: minima

plugins:
  - jekyll-feed

header_pages:
  - work.md
  - notes.md
  - cv.md

collections:
  notes:
    output: true
    permalink: /notes/:name/

markdown: kramdown